### ISSUE TITLE
Stuck in "Requesting. . ."

### ISSUE THREAD

**Issue by NoodleSushi** [Nolkaloid/godot-youtube-dl#1]
I'm using Godot Engine v3.2.stable.official and it get's stuck on `Requesting. . .`
I have already set the certificates option. In the error debugger I get this error 3 times: `~_Thread: Reference to a Thread object was lost while the thread is still running...`
![image](https://user-images.githubusercontent.com/34954180/77285319-aba4e600-6d0b-11ea-9e14-12390334f7a4.png)
![image](https://user-images.githubusercontent.com/34954180/77285338-b2cbf400-6d0b-11ea-9175-5e8aa98db86b.png)
![image](https://user-images.githubusercontent.com/34954180/77285189-684a7780-6d0b-11ea-9c1b-279aa35a230e.png)
![image](https://user-images.githubusercontent.com/34954180/77285220-78625700-6d0b-11ea-8d29-b12f49843035.png)
![image](https://user-images.githubusercontent.com/34954180/77285235-8021fb80-6d0b-11ea-9d92-0250c754f889.png)
[Project Music Theory.zip](https://github.com/Nolkaloid/godot-youtube-dl/files/4367378/Project.Music.Theory.zip)

**Comment by Nolkaloid** [comment]
Hey! Sorry for not noticing the bug report! I will look into that issue tomorrow!

**Comment by Nolkaloid** [comment]
@NoodleSushi Should be fixed now!
